app = "raydelrosario-blog-mysql"
primary_region = "iad"

[build]
  image = "mysql:8"

[mounts]
  source="mysql_data"
  destination="/data"

[env]
  MYSQL_DATABASE = "ghost"
  MYSQL_USER = "ghost"

[processes]
  mysql = "--default-authentication-plugin mysql_native_password --datadir /data/mysql --performance-schema=OFF --innodb-buffer-pool-size 64M"